### ISSUE TITLE
按照你readme.md的步骤调试代码之后出现了一下问题，您能帮忙看一下吗？谢谢！

### ISSUE THREAD

**Issue by liangkai0088** [KimythAnly/deeppacket#1]
您好 ！在github上看到关于deeppacket的代码 我下载了官网上的数据并对代码进行了调试了 ，首先是执行了prepro.py文件，我将数据集解压到了data文件夹下 按照您的步骤修改了代码 但是出现了一下错误，麻烦您能帮我看一下吗？我是一名研究生 十分感谢！！！ 
![tim 20190220100655](https://user-images.githubusercontent.com/31559713/53061857-ea111580-34f9-11e9-8257-4552b5476259.png)
错误提示如下：
(liangkai) [common@precious deeppacket]$ python prepro.py
Using TensorFlow backend.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/common/anaconda2/envs/liangkai/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/common/anaconda2/envs/liangkai/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "prepro.py", line 78, in task
    with open(os.path.join('data', tail+'.pickle'), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/icq_chat_3a.pcap.pickle'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "prepro.py", line 108, in <module>
    res = pool.map(task, todo_list)
  File "/home/common/anaconda2/envs/liangkai/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/common/anaconda2/envs/liangkai/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'data/icq_chat_3a.pcap.pickle'

**Comment by KimythAnly** [comment]
您好


e`热菔钦f]有找到data/icq_chat_3a.pcap.picklen，您的Y料A相ξ恢糜]有O置正_呢？可能是]有找到data@Y料A，您先新增@Y料A再看！


________________________________
寄件者: liangkai0088 <notifications@github.com>
寄件日期: 2019年2月20日 上午 10:27:02
收件者: KimythAnly/deeppacket
副本: Subscribed
主旨: [KimythAnly/deeppacket] 按照你readme.md的步骤调试代码之后出现了一下问题，您能帮忙看一下吗？谢谢！ (#1)


您好 ！在github上看到关于deeppacket的代码 我下载了官网上的数据并对代码进行了调试了 ，首先是执行了prepro.py文件，我将数据集解压到了data文件夹下 按照您的步骤修改了代码 但是出现了一下错误，麻烦您能帮我看一下吗？我是一名研究生 十分感谢！！！
[tim 20190220100655]<https://user-images.githubusercontent.com/31559713/53061857-ea111580-34f9-11e9-8257-4552b5476259.png>
错误提示如下：
(liangkai) [common@precious deeppacket]$ python prepro.py
Using TensorFlow backend.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/home/common/anaconda2/envs/liangkai/lib/python3.6/multiprocessing/pool.py", line 119, in worker
result = (True, func(*args, **kwds))
File "/home/common/anaconda2/envs/liangkai/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
return list(map(*args))
File "prepro.py", line 78, in task
with open(os.path.join('data', tail+'.pickle'), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/icq_chat_3a.pcap.pickle'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "prepro.py", line 108, in
res = pool.map(task, todo_list)
File "/home/common/anaconda2/envs/liangkai/lib/python3.6/multiprocessing/pool.py", line 266, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/home/common/anaconda2/envs/liangkai/lib/python3.6/multiprocessing/pool.py", line 644, in get
raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'data/icq_chat_3a.pcap.pickle'

―

**Comment by KimythAnly** [comment]
您好

錯誤內容是說沒有找到data/icq_chat_3a.pcap.pickle檔，請問您的資料夾相對位置有沒有設置正確呢？可能是沒有找到data這個資料夾，請您先新增這個資料夾再試試看！

**Comment by liangkai0088** [comment]
你好 
我已经按照代码更改了文件相对位置路径，但是官网中的数据集中并没有.pickle文件，只有.pcap和.pcapng文件

**Comment by KimythAnly** [comment]
照理來說那段代碼是在生成 .pickle 文件的，所以你並不需要有 .pickle 文件，他是在生成的時候出錯
請問你有 "precious deeppacket/data" 這個資料夾嗎？

**Comment by spacelover1** [comment]
Hello there, 
I have got the same error and I have checked the relative path, it is correct. I do not know what is the problem. 
![git](https://user-images.githubusercontent.com/17666134/71319684-bce51900-24b6-11ea-92ef-5160ae0e0e49.PNG)

I also have another question, I am working with the same dataset and I need to convert these pcap files to binary sequence, in order to use these sequences to compute entropy, can I use the pickle files for this purpose?

**Comment by liangkai0088** [comment]
Hello, I just opened my email and saw this problem. I solved this problem in three steps:
The first step is to install all third-party dependencies in accordance with the requirements in readme.md. This is important.
The second step, that problem occurred at that time, it seems that it is a problem of multi-threading and files are not found. I added the code to determine the exception to the tool file util.py file. As shown in the photo.
The third step is to configure the path where the vpn-nonvpn file is stored and the path where the pickle file is to be generated.
Just fine

Yes, but I think that if you want to calculate the entropy for the data, I think it is best to use numpy to convert pickle to a calculation matrix before performing the calculation. The above is my suggestion

I'm sorry to reply to you so late, I'm writing a dissertation recently
![TIM图片20191223185841](https://user-images.githubusercontent.com/31559713/71354686-abd00100-25b7-11ea-982f-6c4f517b274c.jpg)

**Comment by liangkai0088** [comment]
> Hello there,
> I have got the same error and I have checked the relative path, it is correct. I do not know what is the problem.
> ![git](https://user-images.githubusercontent.com/17666134/71319684-bce51900-24b6-11ea-92ef-5160ae0e0e49.PNG)
> 
> I also have another question, I am working with the same dataset and I need to convert these pcap files to binary sequence, in order to use these sequences to compute entropy, can I use the pickle files for this purpose?

Hello, I just opened my email and saw this problem. I solved this problem in three steps:
The first step is to install all third-party dependencies in accordance with the requirements in readme.md. This is important.
The second step, that problem occurred at that time, it seems that it is a problem of multi-threading and files are not found. I added the code to determine the exception to the tool file util.py file. As shown in the photo.
The third step is to configure the path where the vpn-nonvpn file is stored and the path where the pickle file is to be generated.
Just fine

Yes, but I think that if you want to calculate the entropy for the data, I think it is best to use numpy to convert pickle to a calculation matrix before performing the calculation. The above is my suggestion

I'm sorry to reply to you so late, I'm writing a dissertation recently
![TIM图片20191223185841](https://user-images.githubusercontent.com/31559713/71354826-16813c80-25b8-11ea-969d-af8235c91611.jpg)

**Comment by spacelover1** [comment]
Thanks a lot, you were right, the problem was that there was no folder for the pickle files to be generated, so I added a folder named "data", and it worked.


> Yes, but I think that if you want to calculate the entropy for the data, I think it is best to use numpy to convert pickle to a calculation matrix before performing the calculation. The above is my suggestion

I didn't get exactly what you mean by "calculation matrix"? 
So I ran this code with one of the pcap files and I got two pickle files:
"email1b.pcap.pickle" ,  "email1b.pcap_class.pickle"
Do you have any ideas how I should deal with these files?

**Comment by liangkai0088** [comment]
The file has a pickle file converted to a Packet Bytes Matrix by numpy，E.g. X_train or X_test .You can take a look after the output. It may be better to find the sequence of X_train to calculate the entropy. The above is only my opinion. If there is something wrong, please point out that I am a Chinese and English is not my native language, so my expression may Not very accurate, you can use Google Translate to translate into Chinese or English to see. Thank you

**Comment by liangkai0088** [comment]
> Thanks a lot, you were right, the problem was that there was no folder for the pickle files to be generated, so I added a folder named "data", and it worked.
> 
> > Yes, but I think that if you want to calculate the entropy for the data, I think it is best to use numpy to convert pickle to a calculation matrix before performing the calculation. The above is my suggestion
> 
> I didn't get exactly what you mean by "calculation matrix"?
> So I ran this code with one of the pcap files and I got two pickle files:
> "email1b.pcap.pickle" , "email1b.pcap_class.pickle"
> Do you have any ideas how I should deal with these files?

The file has a pickle file converted to a Packet Bytes Matrix by numpy，E.g. X_train or X_test .You can take a look after the output. It may be better to find the sequence of X_train to calculate the entropy. The above is only my opinion. If there is something wrong, please point out that I am a Chinese and English is not my native language, so my expression may Not very accurate, you can use Google Translate to translate into Chinese or English to see. Thank you
