### ISSUE TITLE
请问可以上传你们训练好的模型吗？

### ISSUE THREAD

**Issue by JianhaoChung** [KimythAnly/deeppacket#2]
您好，我是一名研究生。目前在研究加密流量分类这一块的内容，希望能够获得你们的模型，并作进一步的研究。

**Comment by KimythAnly** [comment]
嗨，由於這是蠻久以前的專案了，訓練模型並沒有保留下來，不好意思。

**Comment by JianhaoChung** [comment]
CompletePCAPs原始数据集有两个ftp流量文件的size很大，平均大小为5G。我的服务器的内存有47G，Swap分区为16G，按照您代码所示的方法去预处理这两个流量文件时，内存和交换分区跑满了，也无法处理。请问有什么trick可以解决这个问题吗？

**Comment by JianhaoChung** [comment]
还有想请问下，你们实验的效果有像论文中表现那么好吗？

**Comment by KimythAnly** [comment]
你好，我建議你可以使用 dataloader，每次 batch 都一次一次讀進該次 batch 需要的資料並且 preprocess 就好。
至於實驗效果，我印象中當初的表現 f1 能達到 95 左右，詳細數字我也忘記了，感謝你。

**Comment by JianhaoChung** [comment]
感谢您的回复，我想请问你们设置的batch size是多大？readme文件中的示例没有设置该参数。
另外，我们机器硬件遇到性能瓶颈是在：将ftp流量文件的packet（数量很大）去除以太帧包头后，通过np.frombuffer(packet)将raw data 转换为numpy array时。这样单个pcap文件过大以至于无法处理，我们是否可以通过Whireshark工具将pcap包进行裁剪后，再进行prepreocess。
再次感谢！！
